### ISSUE TITLE
Get Kelli's advice on designs.

### ISSUE THREAD

**Issue by thgaskell** [devleague/styles-for-hue#19]
- [x] wireframes/whiteboard what you think it could look like
  - [x] Home page
  - [x] Template view
- [x] describe your user(s)
  - Web developer
  - Designer
- [x] describe features/functions of app (there will be many, prioritize MVP features to nice-to-have features
  - MVP
    - Load stored settings
    - Export CSS
    - Edit / save settings
  - Stetch goals
    - Edit _all_ styles
    - Users
    - Share link

**Comment by ynikki** [comment]
![desktop hd](https://cloud.githubusercontent.com/assets/17637704/19019632/cd67645e-8829-11e6-8573-789684ca86cb.png)
**Our Template View**

**Comment by ynikki** [comment]
**Index Page**

![indexpage](https://cloud.githubusercontent.com/assets/17637704/19019697/cee7da96-882b-11e6-9e48-66732ea0c5c4.png)

**Comment by thgaskell** [comment]
@devleague/styles-for-hue I think a nice stretch goal would allow multiple people to edit the same theme at the same time!
💁
