### ISSUE TITLE
Fix webpack and express running on different processes

### ISSUE THREAD

**Issue by thgaskell** [devleague/styles-for-hue#38]
Currently, express and webpack-dev-server are running as separate processes. webpack-dev-server is actually running express internally. The solution is to use webpack-dev-server programatically.

There's parts of the frontend that have the domain hard-coded in place when it should just be relative domain path. 
(e.g. – `POST http://localhost:3000/api/themes` instead of just `POST /api/themes`)

Check out this [christianalfoni/webpack-express-boilerplate](https://github.com/christianalfoni/webpack-express-boilerplate) as an example for running webpack through express server (only in development mode).

It also eliminates the use of configs via the CLI parameters and moves it into a `webpack.config.js` file.

**Comment by ynikki** [comment]
Closed via #83
