### ISSUE TITLE
Need Kelli's advice on design.

### ISSUE THREAD

**Issue by ynikki** [devleague/styles-for-hue#98]
Getting Kelli's help/advice for design.

**Comment by ynikki** [comment]
## Template Version 01
==================
### Template View with the Edit tab showing...
![version_01 css](https://cloud.githubusercontent.com/assets/17637704/19211473/0791265c-8cd9-11e6-8fc7-34aa2a8edd02.jpeg)

### Template View with the CSS tab showing the css for the user to either copy/view.
![version_01 css](https://cloud.githubusercontent.com/assets/17637704/19211480/36f2aa9c-8cd9-11e6-8614-50254826edd4.jpeg)

### The detail of the functionality of the drop down & the buttons for the edit.
![version_01 details_edit](https://cloud.githubusercontent.com/assets/17637704/19211488/539f7ad0-8cd9-11e6-947f-2f881049ddc7.jpeg)

### The detail of the edit section... 
![version_01 details_css](https://cloud.githubusercontent.com/assets/17637704/19211498/a815b980-8cd9-11e6-9fb1-164f9d2f4f1a.jpeg)

## Template Version 02
==================
![version_02](https://cloud.githubusercontent.com/assets/17637704/19211501/c31bfdfc-8cd9-11e6-9e14-ea77999e6450.jpeg)

## Template Version 03
==================
![version_03](https://cloud.githubusercontent.com/assets/17637704/19211509/ccfa36b8-8cd9-11e6-9c77-8cba65fecff4.jpeg)

**Comment by kellishouts** [comment]
omit the home/about area for now :) (the part you highlighted blue) you could totally add it as a footer item later, since you want to give as much space as possible to the meat of your app!

**Comment by kellishouts** [comment]
either layout looks amazing! tabbed or split view. i'm not sure which one looks better! there are benefits to both:

tabbed view benefits: keeps the focus to designing OR copy-pasta. separation of concerns, for clean UI :D
split view benefits: user can see the code as they mess with toggles above :D good for people that like to see as much stuff at the same time.
